# Generated by Django 3.0.8 on 2020-08-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('latitude_deg', models.FloatField()),
                ('longitude_deg', models.FloatField()),
                ('iata_code', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=300)),
                ('elevation_ft', models.IntegerField()),
                ('iso_country', models.CharField(max_length=3)),
                ('iso_region', models.CharField(max_length=6)),
                ('municipality', models.CharField(max_length=100)),
            ],
        ),
    ]
