# Generated by Django 3.1.4 on 2021-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0003_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportsArrDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=10)),
                ('arrival_func', models.CharField(blank=True, max_length=150, null=True)),
                ('departures_func', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'airports_arr_dep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('acid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('airline', models.CharField(blank=True, max_length=32, null=True)),
                ('arrival_arpt', models.CharField(blank=True, max_length=32, null=True)),
                ('departure_arpt', models.CharField(blank=True, max_length=32, null=True)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'flight_data',
                'managed': False,
            },
        ),
    ]
